#cloud-config
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl - software-properties-common

runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update
  - apt-get install -y docker-ce
  - systemctl enable docker
  - systemctl start docker
  - docker pull nginx
  - docker run -d -p 80:80 nginx