/*
 * Exoscale Public API
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://openapi-v2.exoscale.com/source.json) * [YAML format](https://openapi-v2.exoscale.com/source.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openapiclient.src.main.java.org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.client.model.SecondaryVolumeTarget;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import openapiclient.src.main.java.org.openapitools.client.JSON;

/**
 * Secondary Volume
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-20T18:49:30.768335Z[Etc/UTC]")
public class SecondaryVolumeSnapshot {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_SIZE = "size";
  @SerializedName(SERIALIZED_NAME_SIZE)
  private Long size;

  public static final String SERIALIZED_NAME_CREATED_AT = "created-at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  /**
   * Volume snapshot state
   */
  @JsonAdapter(StateEnum.Adapter.class)
  public enum StateEnum {
    PARTIALLY_DESTROYED("partially-destroyed"),
    
    DESTROYING("destroying"),
    
    CREATING("creating"),
    
    CREATED("created"),
    
    PROMOTING("promoting"),
    
    ERROR("error"),
    
    DESTROYED("destroyed"),
    
    ALLOCATED("allocated");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StateEnum fromValue(String value) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StateEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StateEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StateEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  private StateEnum state;

  public static final String SERIALIZED_NAME_SECONDARY_VOLUME = "secondary-volume";
  @SerializedName(SERIALIZED_NAME_SECONDARY_VOLUME)
  private SecondaryVolumeTarget secondaryVolume;

  public SecondaryVolumeSnapshot() {
  }

  
  public SecondaryVolumeSnapshot(
     UUID id, 
     OffsetDateTime createdAt, 
     StateEnum state
  ) {
    this();
    this.id = id;
    this.createdAt = createdAt;
    this.state = state;
  }

   /**
   * Volume ID
   * @return id
  **/
  @javax.annotation.Nullable
  public UUID getId() {
    return id;
  }




  public SecondaryVolumeSnapshot name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Volume snapshot name
   * @return name
  **/
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public SecondaryVolumeSnapshot size(Long size) {
    
    this.size = size;
    return this;
  }

   /**
   * Volume size
   * minimum: 100
   * maximum: 1024
   * @return size
  **/
  @javax.annotation.Nullable
  public Long getSize() {
    return size;
  }


  public void setSize(Long size) {
    this.size = size;
  }


   /**
   * Volume snapshot creation date
   * @return createdAt
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }




   /**
   * Volume snapshot state
   * @return state
  **/
  @javax.annotation.Nullable
  public StateEnum getState() {
    return state;
  }




  public SecondaryVolumeSnapshot secondaryVolume(SecondaryVolumeTarget secondaryVolume) {
    
    this.secondaryVolume = secondaryVolume;
    return this;
  }

   /**
   * Get secondaryVolume
   * @return secondaryVolume
  **/
  @javax.annotation.Nullable
  public SecondaryVolumeTarget getSecondaryVolume() {
    return secondaryVolume;
  }


  public void setSecondaryVolume(SecondaryVolumeTarget secondaryVolume) {
    this.secondaryVolume = secondaryVolume;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SecondaryVolumeSnapshot secondaryVolumeSnapshot = (SecondaryVolumeSnapshot) o;
    return Objects.equals(this.id, secondaryVolumeSnapshot.id) &&
        Objects.equals(this.name, secondaryVolumeSnapshot.name) &&
        Objects.equals(this.size, secondaryVolumeSnapshot.size) &&
        Objects.equals(this.createdAt, secondaryVolumeSnapshot.createdAt) &&
        Objects.equals(this.state, secondaryVolumeSnapshot.state) &&
        Objects.equals(this.secondaryVolume, secondaryVolumeSnapshot.secondaryVolume);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, size, createdAt, state, secondaryVolume);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SecondaryVolumeSnapshot {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    secondaryVolume: ").append(toIndentedString(secondaryVolume)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("name");
    openapiFields.add("size");
    openapiFields.add("created-at");
    openapiFields.add("state");
    openapiFields.add("secondary-volume");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to SecondaryVolumeSnapshot
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SecondaryVolumeSnapshot.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SecondaryVolumeSnapshot is not found in the empty JSON string", SecondaryVolumeSnapshot.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SecondaryVolumeSnapshot.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SecondaryVolumeSnapshot` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("state") != null && !jsonObj.get("state").isJsonNull()) && !jsonObj.get("state").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `state` to be a primitive type in the JSON string but got `%s`", jsonObj.get("state").toString()));
      }
      // validate the optional field `secondary-volume`
      if (jsonObj.get("secondary-volume") != null && !jsonObj.get("secondary-volume").isJsonNull()) {
        SecondaryVolumeTarget.validateJsonElement(jsonObj.get("secondary-volume"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SecondaryVolumeSnapshot.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SecondaryVolumeSnapshot' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SecondaryVolumeSnapshot> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SecondaryVolumeSnapshot.class));

       return (TypeAdapter<T>) new TypeAdapter<SecondaryVolumeSnapshot>() {
           @Override
           public void write(JsonWriter out, SecondaryVolumeSnapshot value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SecondaryVolumeSnapshot read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SecondaryVolumeSnapshot given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SecondaryVolumeSnapshot
  * @throws IOException if the JSON string is invalid with respect to SecondaryVolumeSnapshot
  */
  public static SecondaryVolumeSnapshot fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SecondaryVolumeSnapshot.class);
  }

 /**
  * Convert an instance of SecondaryVolumeSnapshot to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

